import {test,expect,type BrowserContext} from '@playwright/test';
import {generatePrivateKey,privateKeyToAccount} from 'viem/accounts';
import {mkdirSync} from 'node:fs';
const api='http://127.0.0.1:3002/api/v1';
async function session(context:BrowserContext,name:string){const account=privateKeyToAccount(generatePrivateKey());const ch=await(await fetch(`${api}/auth/challenge`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:account.address})})).json();const signature=await account.signMessage({message:ch.message});const signed=await(await fetch(`${api}/auth/verify`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:ch.id,signature})})).json();const handle=`e2e-${Date.now()}-${name.toLowerCase()}`;await fetch(`${api}/me/profile`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${signed.token}`},body:JSON.stringify({displayName:`Browser ${name}`,handle,role:'Browser test participant',bio:'Automated product flow test account. No onchain work claimed.',skills:['React'],category:'Development',intent:'BOTH'})});return {token:signed.token,handle};}
for(const locale of ['en','zh-CN'] as const)test(`${locale}: client posts, worker applies, client selects and reviews onchain draft`,async({browser})=>{
 const client=await browser.newContext(),worker=await browser.newContext();const cs=await session(client,'Client'),ws=await session(worker,'Worker');
 for(const [context,auth]of [[client,cs],[worker,ws]] as const){await context.addCookies([{name:'pactflow_locale',value:locale,domain:'localhost',path:'/'}]);await context.addInitScript(({token,locale})=>{localStorage.setItem('pactflow_session',token);localStorage.setItem('pactflow_locale',locale);},{token:auth.token,locale});}
 const c=await client.newPage(),w=await worker.newPage();const next=locale==='en'?'Continue':'继续';const title=`[Browser Test] ${locale} dashboard ${Date.now()}`;
 try{await c.goto('/jobs/new');await c.getByLabel(locale==='en'?'Project title':'项目标题',{exact:true}).fill(title);await c.getByLabel(locale==='en'?'Describe the work':'描述工作内容').fill('Build a usable Monad analytics dashboard with three metrics and navigation.');await c.getByLabel(locale==='en'?'Skills (comma separated)':'技能（逗号分隔）').fill('React, TypeScript');await c.getByRole('button',{name:next,exact:true}).click();await c.getByRole('button',{name:next,exact:true}).click();await c.getByRole('button',{name:locale==='en'?'Client Approval':'本人验收',exact:true}).click();await c.getByRole('button',{name:next,exact:true}).click();await c.getByRole('button',{name:next,exact:true}).click();await c.getByRole('button',{name:locale==='en'?'Publish Brief':'发布需求',exact:true}).click();await expect(c.getByText(locale==='en'?'Your brief is live':'需求已发布')).toBeVisible();await c.locator('main a.button').click();await c.waitForURL(/\/jobs\/[0-9a-f-]+$/);const jobUrl=c.url();
 await w.goto('/discover');await w.getByLabel(locale==='en'?'Search briefs or skills':'搜索需求或技能').fill(title);await w.getByRole('heading',{name:title,exact:true}).click();await w.getByRole('button',{name:locale==='en'?'Propose a collaboration':'发起合作提案',exact:true}).click();await w.getByLabel(locale==='en'?'Describe your approach and what you will deliver':'说明你的合作方案与交付成果').fill('I will deliver a working dashboard with reusable React components.');await w.getByLabel(locale==='en'?'I accept the listed budget':'我接受所列预算').check();await w.getByRole('button',{name:locale==='en'?'Send Proposal':'发送合作提案',exact:true}).click();await expect(w.locator('aside').getByText(locale==='en'?'Pending':'待处理',{exact:true})).toBeVisible();
 await c.reload();await c.getByRole('button',{name:locale==='en'?'Choose Partner':'选择合作伙伴',exact:true}).click();await c.getByRole('link',{name:locale==='en'?'Confirm & Lock Funds':'确认合作并锁定资金',exact:true}).click();await expect(c.getByRole('heading',{name:locale==='en'?'Review collaboration':'确认合作内容',exact:true})).toBeVisible();await expect(c.getByText(locale==='en'?'Your wallet confirms creation, token permission, and funding. These are real testnet transactions.':'钱包将确认创建合作、代币授权和资金托管。这些是真实测试网交易。')).toBeVisible();
 mkdirSync('../../docs/screenshots',{recursive:true});await c.screenshot({path:`../../docs/screenshots/draft-${locale}.png`,fullPage:true});
 const jobId=jobUrl.split('/').at(-1);const saved=await(await fetch(`${api}/jobs/${jobId}`)).json();expect(saved.workerDeposit).toBe('0');await fetch(`${api}/jobs/${jobId}/close`,{method:'POST',headers:{Authorization:`Bearer ${cs.token}`}});
 }finally{await client.close();await worker.close();}
});
test('responsive product pages and screenshots',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));mkdirSync('../../docs/screenshots',{recursive:true});const jobs=await(await fetch(`${api}/jobs`)).json();const id=jobs.items[0].id;
 const pages=[['landing','/'],['discover','/discover'],['job-detail',`/jobs/${id}`],['post-job','/jobs/new'],['profile','/u/testnet-worker'],['talent','/talent'],['my-work','/app'],['onboarding','/onboarding'],['notifications','/notifications'],['workspace','/pacts/0x23f57CFa05Cec861d934ee75f16F92A0E419ea9c'],['verification','/verifications/4769dd52-4d32-4d3f-b386-281402e84f9f']] as const;
 for(const [name,url]of pages){await page.goto(url);await page.waitForTimeout(1500);await expect(page.locator('main')).toBeVisible();expect(errors).toEqual([]);if(name==='workspace'){await expect(page.getByText(/Reading Pact from Monad Testnet/)).toHaveCount(0,{timeout:45000});await expect(page.locator('.notice.error')).toHaveCount(0);await expect(page.getByText(/Reading…/)).toHaveCount(0,{timeout:45000});}await page.screenshot({path:`../../docs/screenshots/${name}.png`,fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:`../../docs/screenshots/${name}-mobile.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBeTruthy();await page.setViewportSize({width:768,height:1024});await page.screenshot({path:`../../docs/screenshots/${name}-tablet.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBeTruthy();await page.setViewportSize({width:1440,height:1000});}
});

test('collaboration marketplace: search, category, reset and payment guidance',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:/Good work starts/})).toBeVisible();
 await page.locator('.market-search input').fill('Monad');await page.locator('.market-search button').click();await expect(page).toHaveURL(/discover\?search=Monad/);await expect(page.getByLabel('Search briefs or skills')).toHaveValue('Monad');
 await page.getByRole('button',{name:'Clear filters ×'}).click();await expect(page.getByLabel('Search briefs or skills')).toHaveValue('');
 await page.goto('/');await page.locator('.category-grid').getByRole('link',{name:'Design'}).click();await expect(page.getByLabel('Category')).toHaveValue('Design');
 await page.goto('/');await page.locator('summary').filter({hasText:'Does posting a brief lock any funds?'}).click();await expect(page.getByText('No. A brief and proposals are offchain.',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Language',exact:true}).click();await page.getByRole('button',{name:'简体中文',exact:true}).click();await expect(page.getByRole('heading',{name:/让好的合作/})).toBeVisible();await expect(page.locator('.category-grid').getByRole('link',{name:'设计'})).toBeVisible();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'../../docs/screenshots/landing-zh-CN-hero.png'});await page.screenshot({path:'../../docs/screenshots/landing-zh-CN.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'../../docs/screenshots/landing-zh-CN-mobile.png',fullPage:true});
});


test('form explains invalid fields, prevents mismatched budgets, and removes delivery collateral',async({page})=>{
 await page.goto('/jobs/new');await page.getByLabel('Project title',{exact:true}).fill('Build a Monad app');await page.getByLabel('Describe the work',{exact:true}).fill('dapp');await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByLabel('Describe the work',{exact:true})).toHaveAttribute('aria-invalid','true');await expect(page.locator('.field-error')).toContainText('20–12,000');await page.screenshot({path:'../../docs/screenshots/form-description-error.png'});
 await page.getByLabel('Describe the work',{exact:true}).fill('Build a responsive Monad dashboard with clear navigation and three metrics.');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.locator('.milestone-editor input[type=number]').fill('200');await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.locator('.validation-summary')).toContainText('Milestone amounts must add up');await page.locator('.milestone-editor input[type=number]').fill('300');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByLabel('Expected website URL',{exact:true})).toHaveAttribute('aria-invalid','true');await page.getByLabel('Expected website URL',{exact:true}).fill('https://example.com');await page.getByRole('button',{name:'Continue',exact:true}).click();await expect(page.getByText('No deposit is required from the delivery partner.',{exact:true})).toBeVisible();await expect(page.getByLabel('Delivery partner deposit',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'Language',exact:true}).click();await page.getByRole('button',{name:'简体中文',exact:true}).click();await expect(page.getByText('交付方无需缴纳保证金。',{exact:true})).toBeVisible();await expect(page.locator('main .language-switcher')).toHaveCount(0);await page.screenshot({path:'../../docs/screenshots/payment-protection-zh-CN.png'});await page.reload();await expect(page.getByRole('heading',{name:'发布需求',exact:true})).toBeVisible();await expect(page.locator('header .language-trigger')).toHaveCount(1);
});
